title: Dicey Dungeons
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

nextbuild: 2018-03-30 15:53:04 +0800

plugins:
  - jekyll-feed
  - jekyll-timeago

exclude: [Rakefile]